Update transfer

diff --git a/transfer b/transfer
--- a/transfer
+++ b/transfer
@@ -365,3 +365,83 @@ fi
  echo "" 
  echo "'$4' downloaded successfully to '$2'"
  }
+----------
+# Function to download a file 
+singleDownload() { 
+# Check if download directory exists 
+if [ ! -d "$1" ]; then 
+echo "Download directory '$1' does not exist" 
+exit 1 
+fi 
+# Parse arguments 
+local dir="$1" 
+local id="$2" 
+local filename="$3" 
+# Call printDownloadResponse function to display download progress 
+printDownloadResponse "$dir" "$id" "$filename" 
+} 
+
+# Function to display download response 
+printDownloadResponse() { 
+# Check for missing arguments 
+if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then 
+echo "Missing arguments for download response" 
+exit 1 
+fi 
+# Display download progress 
+echo "Downloading '$3'" 
+echo "" 
+# Show download status 
+while true; do 
+response=$(curl --head --silent "https://transfer.sh/$2/$3" | grep -Fi Content-Length | awk '{print $2}') 
+if [[ -n $response ]]; then 
+break 
+fi 
+done 
+# Print download message 
+fileSize=$(($response/1024)) 
+echo "Download size: ${fileSize} KB" 
+# Download file 
+curl -# --progress-bar "https://transfer.sh/$2/$3" -L -o "$1/$3" 
+# Print download message 
+echo "" 
+echo "'$3' downloaded successfully to '$1'" 
+}
+==========
+# Function to download a file 
+singleDownload() { 
+# Check if download directory exists 
+if [ ! -d "$1" ]; then 
+echo "Download directory '$1' does not exist" 
+exit 1 
+fi 
+# Parse arguments 
+local dir="$1" 
+local id="$2" 
+local filename="$3" 
+# Call printDownloadResponse function to display download progress 
+# printDownloadResponse "$dir" "$id" "$filename" 
+curl https://transfer.sh/"$id"/"$filename" --progress-bar -L -o "$dir"/"$filename"
+} 
+
+---------
+# Option parsing 
+while getopts ":d:hv" opt; do 
+case $opt in 
+d ) # Download file 
+if [ $# -lt $((OPTIND+2)) ]; then 
+echo "Missing arguments for download file option -d" 
+exit 1 
+fi 
+shift $((OPTIND-1)) singleDownload "$1" "$2" "$3" 
+printDownloadResponse "$1" "$2" "$3" 
+exit 0 ;; 
+h ) # Display help 
+printHelp && exit 0 ;; 
+v ) # Display version 
+printVersion && exit 0 ;; 
+\? ) echo "Invalid option: -$OPTARG" 1>&2 && exit 1 ;; 
+: ) echo "Option -$OPTARG requires an argument" 1>&2 && exit 1 ;; 
+esac 
+done
+------------
