Update transfer

diff --git a/transfer b/transfer
--- a/transfer
+++ b/transfer
@@ -188,4 +188,134 @@ printHelp && exit 1
 fi 
 fi
 --------------------
+#!/bin/bash
+
+# Description: Bash tool to transfer files from the command line. 
+# Version: 0.0.1
+
+# Define variables 
+currentVersion="0.0.1" 
+multiUpload=0 
+
+printUploadResponse() {
+echo "Transfer File URL: $fileURL"
+}
+
+# Function to upload a single file
+singleUpload() {
+# Use curl to upload file to transfer.sh
+# curl -# -H "Max-Downloads: 1" -H "Max-Days: 1" --upload-file "$1" "https://transfer.sh/$1"
+response=$(curl -# -H "Max-Downloads: 1" -H "Max-Days: 1" --upload-file "$1" "https://transfer.sh/$1")
+fileURL=$(echo "$response" | cut -f1 -d$'\n')
+# Print file URL
+printUploadResponse
+# echo "Transfer File URL: $fileURL"
+}
+
+# Function to upload multiple files
+multiUpload() {
+# Loop through arguments and upload files to transfer.sh
+for file in "$@"; do
+echo "Uploading $file"
+# curl -# -H "Max-Downloads: 1" -H "Max-Days: 1" --upload-file "$file" "https://transfer.sh/$file"
+# response=$(curl -# -H "Max-Downloads: 1" -H "Max-Days: 1" --upload-file "$file" "https://transfer.sh/$file")
+# Extract the file URL from the response
+fileURL=$(echo "$response" | cut -f1 -d$'\n')
+# Print file URL
+printUploadResponse
+# echo "Transfer File URL: $fileURL"
+done
+}
+
+# Function to download a file 
+# singleDownload() { 
+# Use curl to download file from transfer.sh 
+#curl -# -o "$2/$4" "https://transfer.sh/$3/$4" 
+#}
+
+###########
+
+# Function to download a file 
+singleDownload() { 
+# Parse arguments 
+local dir="${1:?Missing download directory}" 
+local id="${2:?Missing file ID}" 
+local filename="${3:?Missing filename}" 
+
+# Construct download URL 
+local url="https://transfer.sh/$id/$filename" 
+# Display download progress 
+echo "Downloading '$filename'" 
+echo "" 
+# Download file and display progress 
+curl -# -L "$url" --progress-bar -o "$dir/$filename" 
+echo "" 
+echo "'$filename' downloaded successfully to '$dir'" 
+}
+
+# Function to display download response 
+printDownloadResponse() { 
+echo "Downloading '$4'" 
+echo "" 
+while true; do 
+response=$(curl --head --silent "https://transfer.sh/$3/$4" | 
+grep -Fi Content-Length | awk '{print $2}') 
+if [[ -n $response ]]; then 
+break 
+fi 
+done 
+fileSize=$response 
+echo "Download size: $((fileSize/1024)) KB" 
+echo "" 
+curl -# --progress-bar "https://transfer.sh/$3/$4" -L -o "$2/$4" 
+echo "" 
+echo "Success!" 
+} 
+
+# Function to display help messages 
+printHelp() { 
+echo "Description: Bash tool to transfer files from the command line." 
+echo "Version: $currentVersion" 
+echo "" 
+echo "Usage:" 
+echo " -d <dir> <identifier> <filename> Download a file from transfer.sh to specified directory" 
+echo " -h Show help" 
+echo " -v Show version" 
+echo "" 
+echo "Examples:" 
+echo " Upload a file:" 
+echo " ./transfer.sh test.txt" 
+echo "" 
+echo " Upload multiple files:" 
+echo " ./transfer.sh test1.txt test2.png test3.pdf" 
+echo "" 
+echo " Download a file:" 
+echo " ./transfer.sh -d ./dir xxxxxx file.txt" 
+} 
+
+# Option parsing 
+while getopts ":d:hv" opt; do 
+case $opt in 
+d ) # Download file 
+singleDownload $optind "$OPTARG" "${@:$optind + 1:2}" 
+printDownloadResponse $optind "$OPTARG" "${@:$optind + 1:2}" && exit 0 ;; 
+h ) # Display help 
+printHelp && exit 0 ;; 
+v ) # Display version 
+printVersion && exit 0 ;; 
+\? ) echo "Invalid option: -$OPTARG" 1>&2 && exit 1 ;; 
+: ) echo "Option -$OPTARG requires an argument" 1>&2 && exit 1 ;; 
+esac 
+done 
+
+# Upload files if no options were specified 
+if [ $OPTIND -eq 1 ]; then 
+if [ $# -eq 1 ]; then 
+singleUpload "$1" 
+elif [ $# -gt 1 ]; then 
+multiUpload "$@" 
+else 
+echo "No files specified" 
+fi 
+fi
 
